[project]
name = "ftcvanguard"
version = "0.1.0"
description = "A real-time scouting app for FIRST Tech Challenge with advanced, real time insights."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyjwt[crypto]>=2.10.1",
    "requests>=2.32.5",
    "scipy>=1.16.3",
]
